version: '3.9'
services:
  libraw:
    hostname: libraw
    container_name: libraw
    image: ai2ys/dockerized-libraw:${VERSION_LIBRAW}
    build:
      context: .
      dockerfile: dockerfile
      args:
        VERSION_LIBRAW:
    tty: true
    volumes:
      - ${DATA_DIR:-.}:/workspace